services:
  reddit_chat_bridge:
    image: ghcr.io/mmenanno/reddit_chat_bridge:latest
    container_name: reddit_chat_bridge
    restart: unless-stopped
    user: "1000:1000"
    ports:
      - "4567:4567"
    volumes:
      - ./state:/app/state
